### ISSUE TITLE
Could not find a declaration file for module 'node-php-password'. 'c:/project/node_modules/node-php-password/index.js' implicitly has an 'any' type.   Try `npm i --save-dev @types/node-php-password` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-php-password'

### ISSUE THREAD

**Issue by leccyril** [alrek-consulting/node-php-password#6]
Hello, 

i am using vuejs.

i installed the lib from gui => ok 

but let Password = require('node-php-password') create me an error mentioned above. Have you an idea ? 

thanks

**Comment by thomas-alrek** [comment]
Hi, seems like you are using typescript. Unfortunately I haven't added types for it. I probably don't have any time in the near future unfortunately. But please feel free to create a PR, and I will gladly merge it.
